# To create the conda environment, run:
#   conda env create -f environment.yml
name: search-engine
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - python=3.13.3
  - pytorch=2.6
  - pandas=2.2.3
  - numpy=2.2.5
  - scipy=1.15.2
  - wandb=0.19.8
  - tqdm=4.67.1
  - pyarrow=19.0.1
