name: ss-env
channels:
  - defaults
  - conda-forge
  - huggingface
dependencies:
  - python=3.10
  - pip
  - numpy=2.2.4
  - pandas
  - matplotlib
  - scipy
  - pytorch
  - conda-forge::datasets
  - conda-forge::wandb
  - tqdm
  - pre-commit
  - streamlit
  - pip:
    - wandb
    - fastparquet
